In [10]:
import pandas as pd

# Load the CSV
df = pd.read_csv("fred_data.csv")

In [21]:
non_empty = df[df["es_orig"].notna() & (df["es_orig"] != " ")]

In [29]:
for row in non_empty[["es_original", "es_orig"]].iterrows():
    print(row[0], row[1])

267 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 267, dtype: object
268 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 268, dtype: object
269 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 269, dtype: object
270 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 270, dtype: object
271 es_original    0.330350424728106
es_orig            d = .70 ± .46
Name: 271, dtype: object
272 es_original       NaN
es_orig        d = NR
Name: 272, dtype: object
273 es_original    0.287347885566345
es_orig            d = .60 ± .55
Name: 273, dtype: object
274 es_original    0.287347885566345
es_orig            d = .60 ± .55
Name: 274, dtype: object
275 es_original    0.282945147243684
es_orig           d = -.59 ± .55
Name: 275, dtype: object
276 es_original    0.282945147243684
es_orig           d = -.59 ± .55
Name: 276, dtype: object
277 es_original    0.282945147243684
es_orig           d = -.59 ± .55
Name: 277, dtype: object
278 es_original    0.282945147243684
es_orig           d = -.59 ± .55
Name: 278, dtype: object
279 es_original    0.511332767400783
es_orig          d = -1.19 ± .52
Name: 279, dtype: object
280 es_original    0.443625153753289
es_orig           d = -.99 ± .52
Name: 280, dtype: object
281 es_original    0.351123441588392
es_orig           d = -.75 ± .71
Name: 281, dtype: object
282 es_original    0.61989867506062
es_orig         d = -1.58 ± .98
Name: 282, dtype: object
283 es_original    0.181913199610981
es_orig           d = -.37 ± .44
Name: 283, dtype: object
284 es_original    0.181913199610981
es_orig           d = -.37 ± .44
Name: 284, dtype: object
285 es_original    0.181913199610981
es_orig           d = -.37 ± .44
Name: 285, dtype: object
286 es_original    0.468293636983821
es_orig          d = -1.06 ± .71
Name: 286, dtype: object
287 es_original    0.454326082796012
es_orig           d = 1.02 ± .76
Name: 287, dtype: object
288 es_original    0.454326082796012
es_orig           d = 1.02 ± .76
Name: 288, dtype: object
289 es_original    0.454326082796012
es_orig           d = 1.02 ± .76
Name: 289, dtype: object
290 es_original    0.454326082796012
es_orig           d = 1.02 ± .76
Name: 290, dtype: object
291 es_original    0.454326082796012
es_orig           d = 1.02 ± .76
Name: 291, dtype: object
292 es_original    0.363345276491644
es_orig            d = .78 ± .62
Name: 292, dtype: object
293 es_original    0.363345276491644
es_orig            d = .78 ± .62
Name: 293, dtype: object
294 es_original    0.363345276491644
es_orig            d = .78 ± .62
Name: 294, dtype: object
295 es_original    0.363345276491644
es_orig            d = .78 ± .62
Name: 295, dtype: object
296 es_original    0.363345276491644
es_orig            d = .78 ± .62
Name: 296, dtype: object
297 es_original    0.375382367719639
es_orig            d = .81 ± .73
Name: 297, dtype: object
298 es_original    0.375382367719639
es_orig            d = .81 ± .73
Name: 298, dtype: object
299 es_original    0.517637881190732
es_orig           d = 1.21 ± .55
Name: 299, dtype: object
300 es_original    0.517637881190732
es_orig           d = 1.21 ± .55
Name: 300, dtype: object
301 es_original    0.517637881190732
es_orig           d = 1.21 ± .55
Name: 301, dtype: object
302 es_original    0.517637881190732
es_orig           d = 1.21 ± .55
Name: 302, dtype: object
303 es_original             0.38
es_orig        r = .38 ± .30
Name: 303, dtype: object
304 es_original             0.38
es_orig        r = .38 ± .30
Name: 304, dtype: object
305 es_original             0.45
es_orig        r = .45 ± .31
Name: 305, dtype: object
306 es_original             0.45
es_orig        r = .45 ± .31
Name: 306, dtype: object
307 es_original             0.45
es_orig        r = .45 ± .31
Name: 307, dtype: object
308 es_original             0.45
es_orig        r = .45 ± .31
Name: 308, dtype: object
309 es_original             0.45
es_orig        r = .45 ± .31
Name: 309, dtype: object
310 es_original             0.45
es_orig        r = .45 ± .31
Name: 310, dtype: object
311 es_original             0.33
es_orig        r = .33 ± .26
Name: 311, dtype: object
312 es_original             0.33
es_orig        r = .33 ± .26
Name: 312, dtype: object
313 es_original             0.33
es_orig        r = .33 ± .26
Name: 313, dtype: object
314 es_original    0.282945147243684
es_orig            d = .59 ± .51
Name: 314, dtype: object
315 es_original    0.282945147243684
es_orig            d = .59 ± .51
Name: 315, dtype: object
316 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 316, dtype: object
317 es_original    0.300049290385153
es_orig               OR = 3.13
Name: 317, dtype: object
318 es_original    0.124034734589208
es_orig                  d = .25
Name: 318, dtype: object
319 es_original    0.269629925519971
es_orig            d = .56 ± .43
Name: 319, dtype: object
320 es_original    0.177152998315265
es_orig            d = .36 ± .21
Name: 320, dtype: object
321 es_original    0.177152998315265
es_orig            d = .36 ± .21
Name: 321, dtype: object
322 es_original    0.124034734589208
es_orig            d = .25 ± .25
Name: 322, dtype: object
323 es_original    0.351123441588392
es_orig            d = .75 ± .52
Name: 323, dtype: object
324 es_original    0.351123441588392
es_orig            d = .75 ± .52
Name: 324, dtype: object
325 es_original             0.29
es_orig        r = .29 ± .21
Name: 325, dtype: object
326 es_original             0.57
es_orig        r = .57 ± .19
Name: 326, dtype: object
327 es_original             0.57
es_orig        r = .57 ± .19
Name: 327, dtype: object
328 es_original             0.57
es_orig        r = .57 ± .19
Name: 328, dtype: object
329 es_original             0.57
es_orig        r = .57 ± .19
Name: 329, dtype: object
330 es_original             0.57
es_orig        r = .57 ± .19
Name: 330, dtype: object
331 es_original             0.57
es_orig        r = .57 ± .19
Name: 331, dtype: object
332 es_original             0.57
es_orig        r = .57 ± .19
Name: 332, dtype: object
333 es_original             0.57
es_orig        r = .57 ± .19
Name: 333, dtype: object
334 es_original             0.57
es_orig        r = .57 ± .19
Name: 334, dtype: object
335 es_original             0.57
es_orig        r = .57 ± .19
Name: 335, dtype: object
336 es_original             0.57
es_orig        r = .57 ± .19
Name: 336, dtype: object
337 es_original             0.57
es_orig        r = .57 ± .19
Name: 337, dtype: object
338 es_original             0.57
es_orig        r = .57 ± .19
Name: 338, dtype: object
339 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 339, dtype: object
340 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 340, dtype: object
341 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 341, dtype: object
342 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 342, dtype: object
343 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 343, dtype: object
344 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 344, dtype: object
345 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 345, dtype: object
346 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 346, dtype: object
347 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 347, dtype: object
348 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 348, dtype: object
349 es_original    0.395027750659415
es_orig            d = .86 ± .74
Name: 349, dtype: object
350 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 350, dtype: object
351 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 351, dtype: object
352 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 352, dtype: object
353 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 353, dtype: object
354 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 354, dtype: object
355 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 355, dtype: object
356 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 356, dtype: object
357 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 357, dtype: object
358 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 358, dtype: object
359 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 359, dtype: object
360 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 360, dtype: object
361 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 361, dtype: object
362 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 362, dtype: object
363 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 363, dtype: object
364 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 364, dtype: object
365 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 365, dtype: object
366 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 366, dtype: object
367 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 367, dtype: object
368 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 368, dtype: object
369 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 369, dtype: object
370 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 370, dtype: object
371 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 371, dtype: object
372 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 372, dtype: object
373 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 373, dtype: object
374 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 374, dtype: object
375 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 375, dtype: object
376 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 376, dtype: object
377 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 377, dtype: object
378 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 378, dtype: object
379 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 379, dtype: object
380 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 380, dtype: object
381 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 381, dtype: object
382 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 382, dtype: object
383 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 383, dtype: object
384 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 384, dtype: object
385 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 385, dtype: object
386 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 386, dtype: object
387 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 387, dtype: object
388 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 388, dtype: object
389 es_original    0.114247022914439
es_orig            d = .23 ± .25
Name: 389, dtype: object
390 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 390, dtype: object
391 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 391, dtype: object
392 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 392, dtype: object
393 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 393, dtype: object
394 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 394, dtype: object
395 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 395, dtype: object
396 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 396, dtype: object
397 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 397, dtype: object
398 es_original    0.242535625036333
es_orig                  d = .50
Name: 398, dtype: object
399 es_original    0.242535625036333
es_orig                  d = .50
Name: 399, dtype: object
400 es_original    0.242535625036333
es_orig                  d = .50
Name: 400, dtype: object
401 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 401, dtype: object
402 es_original    0.242535625036333
es_orig                  d = .50
Name: 402, dtype: object
403 es_original    0.242535625036333
es_orig                  d = .50
Name: 403, dtype: object
404 es_original    0.242535625036333
es_orig                  d = .50
Name: 404, dtype: object
405 es_original    0.242535625036333
es_orig                  d = .50
Name: 405, dtype: object
406 es_original    0.242535625036333
es_orig                  d = .50
Name: 406, dtype: object
407 es_original    0.242535625036333
es_orig                  d = .50
Name: 407, dtype: object
408 es_original    0.242535625036333
es_orig                  d = .50
Name: 408, dtype: object
409 es_original    0.242535625036333
es_orig                  d = .50
Name: 409, dtype: object
410 es_original    0.242535625036333
es_orig                  d = .50
Name: 410, dtype: object
411 es_original    0.242535625036333
es_orig                  d = .50
Name: 411, dtype: object
412 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 412, dtype: object
413 es_original    0.242535625036333
es_orig                  d = .50
Name: 413, dtype: object
414 es_original    0.242535625036333
es_orig                  d = .50
Name: 414, dtype: object
415 es_original    0.242535625036333
es_orig                  d = .50
Name: 415, dtype: object
416 es_original    0.242535625036333
es_orig                  d = .50
Name: 416, dtype: object
417 es_original    0.242535625036333
es_orig                  d = .50
Name: 417, dtype: object
418 es_original    0.242535625036333
es_orig                  d = .50
Name: 418, dtype: object
419 es_original    0.242535625036333
es_orig                  d = .50
Name: 419, dtype: object
420 es_original    0.242535625036333
es_orig                  d = .50
Name: 420, dtype: object
421 es_original    0.242535625036333
es_orig                  d = .50
Name: 421, dtype: object
422 es_original    0.242535625036333
es_orig                  d = .50
Name: 422, dtype: object
423 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 423, dtype: object
424 es_original    0.242535625036333
es_orig                  d = .50
Name: 424, dtype: object
425 es_original    0.242535625036333
es_orig                  d = .50
Name: 425, dtype: object
426 es_original    0.242535625036333
es_orig                  d = .50
Name: 426, dtype: object
427 es_original    0.242535625036333
es_orig                  d = .50
Name: 427, dtype: object
428 es_original    0.242535625036333
es_orig                  d = .50
Name: 428, dtype: object
429 es_original    0.242535625036333
es_orig                  d = .50
Name: 429, dtype: object
430 es_original    0.242535625036333
es_orig                  d = .50
Name: 430, dtype: object
431 es_original    0.242535625036333
es_orig                  d = .50
Name: 431, dtype: object
432 es_original    0.242535625036333
es_orig                  d = .50
Name: 432, dtype: object
433 es_original    0.242535625036333
es_orig                  d = .50
Name: 433, dtype: object
434 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 434, dtype: object
435 es_original    0.242535625036333
es_orig                  d = .50
Name: 435, dtype: object
436 es_original    0.242535625036333
es_orig                  d = .50
Name: 436, dtype: object
437 es_original    0.242535625036333
es_orig                  d = .50
Name: 437, dtype: object
438 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 438, dtype: object
439 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 439, dtype: object
440 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 440, dtype: object
441 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 441, dtype: object
442 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 442, dtype: object
443 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 443, dtype: object
444 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 444, dtype: object
445 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 445, dtype: object
446 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 446, dtype: object
447 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 447, dtype: object
448 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 448, dtype: object
449 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 449, dtype: object
450 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 450, dtype: object
451 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 451, dtype: object
452 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 452, dtype: object
453 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 453, dtype: object
454 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 454, dtype: object
455 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 455, dtype: object
456 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 456, dtype: object
457 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 457, dtype: object
458 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 458, dtype: object
459 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 459, dtype: object
460 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 460, dtype: object
461 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 461, dtype: object
462 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 462, dtype: object
463 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 463, dtype: object
464 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 464, dtype: object
465 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 465, dtype: object
466 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 466, dtype: object
467 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 467, dtype: object
468 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 468, dtype: object
469 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 469, dtype: object
470 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 470, dtype: object
471 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 471, dtype: object
472 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 472, dtype: object
473 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 473, dtype: object
474 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 474, dtype: object
475 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 475, dtype: object
476 es_original    0.450780571280258
es_orig                 d = 1.01
Name: 476, dtype: object
477 es_original    0.514495755427527
es_orig           d = 1.20 ± .26
Name: 477, dtype: object
478 es_original    0.359291737742147
es_orig            d = .77 ± .74
Name: 478, dtype: object
479 es_original    0.514495755427527
es_orig           d = 1.20 ± .26

In [12]:
for c in df.columns:
    print(c)

id
rowid
temp
status
cos
validated
validated_person
source
discipline
effect
tags
description
claim_text_orig
claim_statistics_orig
claim_statistics_orig_page
claim_text_orig_page
notes
contributors
date_entered
date_updated
notes_validation
exclusion
es_original
es_replication
n_original
n_replication
ref_original
doi_original
refonly_original
study_original
ref_replication
doi_replication
refonly_replication
study_replication
es_orig
es_rep
es_orig_value
es_orig_estype
es_rep_value
es_rep_estype
pval_value_o
pval_type_o
pval_tails_o
pval_value_r
pval_type_r
pval_tails_r
es_orig_RRR
es_orig_RRR_estype
es_rep_RRR
es_rep_RRR_estype
osf_link
outcome
published_rep
id_sample
same_design
nesting
same_test
original_authors
study_orig
study_rep
teststatistic_orig
teststatistic_rep
p_es_orig
p_es_rep
p_n_orig
p_n_rep
p_p_orig
p_p_rep
result
preregistration
closeness_instructions
closeness_measures
closeness_stimuli
closeness_procedure
closeness_location
closeness_renumeration
closeness_participants
closeness_exclusions
closeness_language
closeness_nationality
differences
vi_orig
vi_rep
ci.lower_original
ci.upper_original
ci.lower_replication
ci.upper_replication
significant_original
significant_replication
power
orig_journal
X92
X93
X94
X95
both_pdfs
ON_COS_SHEET
DOI_changed
dupl
count
contributor_emailaddress
contributor_country
completed
#
Link/Reference.for.the.replication.study
Type
Priority?
Study.listed.in.ReD?
entry.completed.here?
Data.entered.into.ReD?
Field?
field

In [4]:
len(df)

5652

In [5]:
df = df.dropna(subset=["es_original", "es_replication"])

In [6]:
len(df)

1234

In [7]:

# Drop rows where both are exactly 0.0
df = df[~((df["es_original"] == 0.0) & (df["es_replication"] == 0.0))]

In [30]:
# Load the CSV
df = pd.read_excel("FReD.xlsx")

In [31]:
len(df)

4661

In [34]:
df = df.dropna(subset=["es_original", "es_replication"])
df = df[~((df["es_original"] == 0.0) & (df["es_replication"] == 0.0))]

In [35]:
len(df)

1230

In [36]:

# Save cleaned version
df.to_csv("fred_data_cleaned.csv", index=False)

print(f"Cleaned dataset saved to fred_data_clean.csv — {len(df)} rows remaining.")

Cleaned dataset saved to fred_data_clean.csv — 1230 rows remaining.

In [41]:
import pandas as pd

# Load both CSVs
fred_data = pd.read_csv("fred_data.csv")

In [42]:
len(fred_data)

1230

In [43]:
fred_reversal = pd.read_csv("fred_reversal.csv", usecols=["result", "description"])

# Rename 'result' column in fred_reversal
fred_reversal = fred_reversal.rename(columns={"result": "result_alt"})

# Merge based on matching 'description' values
merged = fred_data.merge(
    fred_reversal[["description", "result_alt"]],
    on="description",
    how="left"
)

# Save or inspect
merged.to_csv("fred_merged.csv", index=False)

In [44]:
len(merged)

1643

In [45]:
df2 = pd.read_csv("fred_data.csv")

In [46]:
set(df2['result'])

{'#',
 'inconclusive',
 'informative failure to replicate',
 nan,
 'success',
 'success, informative failure to replicate, practical failure to replicate, inconclusive',
 'success, informative failure to replicate, practical failure to replicate, inconclusive [taken from the respective reports and if not reported automatically computed; success = both effects are significant in the same direction]'}